### ISSUE TITLE
depositing collateral too expensive?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#33]
![image](https://user-images.githubusercontent.com/57764578/196233886-c58e395f-2684-49f9-be14-e3cb140b3d23.png)

I got trouble depositing collateral
The price is 0.42 goerli ETH
Is this network congestion or because our smart contract is very expensive to make any change?

**Comment by Morteza3123** [comment]
When require() line of a function doenst accept you it will failed, so metamask found it and show high gas. If you see this high gas, dont confirm because it will failed. 
For example you move price far from oracle it will be failed so metamask shows high gas for transaction. (in the front end we will show error to user befor showing metamak)
