### ISSUE TITLE
ActiveUsers list will keep expanding because empty entries are not dropped or sliced

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#41]
The 10.GetAllActiveUsers list is a list that keeps expanding, instead of removing it changes an address into 0x000...  (so empty)
it seems. So the list will get longer.

line 132: delete activeUsers[i];

**Comment by Morteza3123** [comment]
Yes, It's because of solidity language. When you romve an element from your array, It will be cleaned but the place remains empty.

However in related functions I check that if user was zero address the function skip that. 

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/794b34e5f509a489d5152f64f10c1383f7f39b1e/contracts/Exchange.sol#L856

**Comment by Waltermelon-lang** [comment]
And are you not worried that in time, this will blow up this user list? (and with it increase the gas costs?)

**Comment by Morteza3123** [comment]
When function see that it's zero address, skips it, and we don't pay gas for that.

**Comment by Waltermelon-lang** [comment]
Oke thats very nice!
