### ISSUE TITLE
save gas or liquidationCover

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#55]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L1061

I like the code but perhaps you can save gas by not casting it into a seperate variable but just immediately substracting it. 

If not I would like to change the name userFundingFee  to liquidationCover because it is something different than 
the funding fee.

**Comment by Morteza3123** [comment]
But this change does not gas cost significantly, because it's a function variable and we just use it in the function ( something like libraries). This just makes code harder to read. 

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c271dc021cb575f80e83497688f92333cb0c6e9f/contracts/Exchange.sol#L792

**Comment by Waltermelon-lang** [comment]
Oke I get all of it. Apologies, never mind.
