### ISSUE TITLE
vBaycNewPoolSize -> _vBaycNewPoolSize and back to vBaycNewPoolSize

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#59]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L680-L690

Is the conversion from _vBaycNewPoolSize to vBaycNewPoolSize necassary? Since the input and the output of the function is to modify the vBaycNewPoolSize variable itself?

  (vBaycNewPoolSize, vUsdNewPoolSize) = _hardLiquidate(activeUsers[i], vBaycNewPoolSize, vUsdNewPoolSize)

**Comment by Morteza3123** [comment]
The reason as you said is that in this loop I need to update newPoolSize for each user. And next Usdr should have new updated poolsize of last user that has been liquidated.

If I use _vBaycNewPoolSize for input of the loop liquidate functions, I still liqudate users with same pool size. I initial _vBaycNewPoolSize in the new variable to easily change it dure the each loop, because I can't change input of function diractly. I don't know is it clear to you or you have question about some thing more.

**Comment by Waltermelon-lang** [comment]
No I get it, thats just specific to the solidity language I assume. No changes needed.
