### ISSUE TITLE
unintuitive sign

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#67]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e0b3f246301585967665e5f3dfc4443f38f02f94/utils/exchange.ts#L116

 Pool.updateUserCollateral ->
From the name of this function I cannot tell whether collateral will be removed or added. In 
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/main/contracts/Exchange.sol
we have a deposit- and withdraw-collateral function. Therefore I would say a positive amount, is positively added to the collateral. This is the 'default' and flipping that might lead to confusion.

**Comment by crazy-dev-git** [comment]
@Waltermelon-lang 
I will split this two functions - deposit and withdraw collateral.
Anyway, I am confusing regarding collateral balance because of unrealized and realized PNL.
Now we add or sub collateral value as unrealized profit or loss.
And in withdraw-collateral function, users can withdraw collateral from this.
[https://github.com/nexlabs22/Nex-Dex-Contracts/pull/69](url)
I couldn't see the difference of unrealized PNL and realized PNL.

**Comment by Waltermelon-lang** [comment]
When we realize unrealized profit 
its like this:
 collateral[usdc][_user] +-= pnl;
 Where PNL is a variable not stored in memory. When unrealized PNL gets 'realized' it basically just means we are closing the position and transfer any remainder virtual usdc balance to the real usdc balance.
 When we deposit or withdraw collateral, it has nothing to do with PNL, only with the collateral.
 We don't work with 'realized' PNL as a variable afaik.
Hope this helps, please refer me some code lines if you have further unclarities.
